# Generated by Django 4.1 on 2024-05-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publishing_House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("date_of_opening", models.DateField()),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
                ("isbn", models.CharField(max_length=100)),
                ("number_of_pages", models.IntegerField()),
                ("dimension_of_book", models.CharField(max_length=80)),
                (
                    "type_of_book",
                    models.CharField(
                        choices=[("SF", "Soft"), ("HR", "Hard")], max_length=3
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ROM", "Romance"),
                            ("TRI", "Thriller"),
                            ("BIO", "Biography"),
                            ("CLS", "Classic"),
                            ("DRA", "Drama"),
                            ("HIS", "History"),
                        ],
                        max_length=4,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "publishing_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_app.publishing_house",
                    ),
                ),
            ],
        ),
    ]
