# Generated by Django 4.1 on 2024-05-21 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="year_of_publish",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
